// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASCXAQvCH2H8kOA1AwjWRYM-EUSvjcJFk',
    appId: '1:701385862827:web:c4f6194af5d88ead6011ee',
    messagingSenderId: '701385862827',
    projectId: 'amst-flutter-db-72335',
    authDomain: 'amst-flutter-db-72335.firebaseapp.com',
    databaseURL: 'https://amst-flutter-db-72335-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-72335.appspot.com',
    measurementId: 'G-BXZ2DY1X0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz5hnMegTm-Z7zflNPM1uqzskQ1n2ByfA',
    appId: '1:701385862827:android:c313b2c2bd341e746011ee',
    messagingSenderId: '701385862827',
    projectId: 'amst-flutter-db-72335',
    databaseURL: 'https://amst-flutter-db-72335-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-72335.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMg8opqky67LuYRmeuMTf6wracVAJX07g',
    appId: '1:701385862827:ios:6c75eda189a894c26011ee',
    messagingSenderId: '701385862827',
    projectId: 'amst-flutter-db-72335',
    databaseURL: 'https://amst-flutter-db-72335-default-rtdb.firebaseio.com',
    storageBucket: 'amst-flutter-db-72335.appspot.com',
    iosBundleId: 'com.amst.appFlutterDb',
  );
}
